import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import {
  Inter as FontSans,
  Inter,
  Lexend,
  Outfit,
  Poppins,
  Quicksand,
  Work_Sans,
} from "next/font/google";
import "./custom.css";
import "./globals.css";
import { FooterSection, NavbarSection, Providers } from "@/components";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const lexend = Lexend({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

//lexend

// quick Sand

export const metadata: Metadata = {
  title: "Kitty Start",
  description: "Generated by create next app",
};

export default function LandingRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased light",
          poppins.variable,
          lexend.className
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
